changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - semver-major
    - title: Features
      labels:
        - feature
        - enhancement
        - semver-minor
    - title: Fixes
      labels:
        - bug
        - fix
        - semver-patch
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: CI and Maintenance
      labels:
        - ci
        - maintenance
        - dependencies
    - title: Other Changes
      labels:
        - "*"
